{"uuid": "fc1cecc4-ceac-4148-961e-d6a0f6c038b9", "children": ["28a7cc04-4a49-4ccb-8bb5-c9451b89e731"], "befores": [{"name": "start_flow", "status": "passed", "start": 1644545122491, "stop": 1644545135047}], "afters": [{"name": "start_flow::0", "status": "broken", "statusDetails": {"message": "TypeError: not all arguments converted during string formatting\n", "trace": "  File \"d:\\program files(x86)\\python3.7\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\program files(x86)\\python3.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"E:\\LuxFlow_front\\testcase\\conftest.py\", line 18, in start_flow\n    main.main_quit()\n  File \"E:\\LuxFlow_front\\flow_page\\main_page.py\", line 221, in main_quit\n    LogRoot.error(\"报错处理\", e)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 1412, in error\n    self._log(ERROR, msg, args, **kwargs)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 1519, in _log\n    self.handle(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 1529, in handle\n    self.callHandlers(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 1591, in callHandlers\n    hdlr.handle(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 905, in handle\n    self.emit(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\site-packages\\_pytest\\logging.py\", line 331, in emit\n    super().emit(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 1040, in emit\n    self.handleError(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 1034, in emit\n    msg = self.format(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 880, in format\n    return fmt.format(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\site-packages\\_pytest\\logging.py\", line 92, in format\n    return super().format(record)\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 619, in format\n    record.message = record.getMessage()\n  File \"d:\\program files(x86)\\python3.7\\lib\\logging\\__init__.py\", line 380, in getMessage\n    msg = msg % self.args\n"}, "start": 1644545551781, "stop": 1644545557714}], "start": 1644545122491, "stop": 1644545557714}